# 配置Tomcat属性
server:
  port: 8443
  error:
    path: /error
  servlet:
    context-path: /dev
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    basedir: E:/Program Files/Apache Software Foundation/Tomcat 9.0/temp
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store-password: changeit
    key-store-provider: SUN
    key-store-type: JKS
    key-store: classpath:ssl-server.jks

# 配置属性
music:
  name: music000
  artist: aaa
  playCount: 3000
  description: ${music.name}by${music.artist}
#  comments:
#    - good
#    - nice
#    - excellent
  rank:
    january: 1
    february: 2
    march: 1
  comments: [good, Nice, excellent]
# rank: {january:1, february:2, march:1}